### ISSUE TITLE
Fails to build with Qt 5.5.1 (Ubuntu 16.04)

### ISSUE THREAD

**Issue by hotice** [mmozeiko/RcloneBrowser#5]
Fails to build in Ubuntu 16.04 with Qt 5.5.1, with the following error:
```
[ 70%] Building CXX object src/CMakeFiles/rclone-browser.dir/item_model.cpp.o
/<<PKGBUILDDIR>>/src/item_model.cpp: In function ‘void {anonymous}::advanceSpinner(QString&)’:
/<<PKGBUILDDIR>>/src/item_model.cpp:659:1: error: assuming signed overflow does not occur when assuming that (X - c) <= X is always true [-Werror=strict-overflow]
 }
 ^
cc1plus: all warnings being treated as errors
src/CMakeFiles/rclone-browser.dir/build.make:416: recipe for target 'src/CMakeFiles/rclone-browser.dir/item_model.cpp.o' failed
make[4]: *** [src/CMakeFiles/rclone-browser.dir/item_model.cpp.o] Error 1
```
You can go around this by adding ``-Wno-error=strict-overflow`` but I thought you might want to check it anyway. The complete build log is available here: https://launchpadlibrarian.net/304436289/buildlog_ubuntu-xenial-amd64.rclone-browser_1.0.0-1~webupd8~xenial0_BUILDING.txt.gz

**Comment by mmozeiko** [comment]
Interesting, I tried compiling on 14.04 and 16.10 and didn't get any errors.
I'll fix the code later today.

**Comment by mmozeiko** [comment]
Can you please try with latest commit c1ad5f8? It should now build fine on 16.04.

**Comment by hotice** [comment]
This fixes it, thank you! The issue was not occurring on my local machine, but in a Launchpad PPA (I uploaded Rclone Browser to a PPA to make it easy for UIbuntu / Linux Mint users to install it) repository which has some different defaults...

**Comment by maverickdas** [comment]
I was facing this problem on Arch Linux as well. The [change](https://github.com/mmozeiko/RcloneBrowser/issues/5#issue-203987884) suggested by @hotice fixed it.
